# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import glob
import os
import shutil

# -- Project information -----------------------------------------------------
project = "Health ML Tutorial"
copyright = "2026, Gaël Varoquaux"
author = "Gaël Varoquaux"
release = "0.1"

# -- General configuration ---------------------------------------------------
# sphinx_gallery.gen_gallery must be listed before jupyterlite_sphinx so
# that sphinx-gallery's build-finished hook (create_jupyterlite_contents)
# runs before jupyterlite-sphinx's build-finished hook (jupyterlite_build).
# This ensures the notebooks are copied into jupyterlite_contents/ before
# JupyterLite is built. The config-inited ordering is handled by explicit
# priorities inside sphinx-gallery and does not depend on this order.
extensions = [
    "sphinx_gallery.gen_gallery",
    "jupyterlite_sphinx",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

html_sidebars = {
    "**": [
        # Sphinx-Gallery sidebar components (launch buttons)
        # https://sphinx-gallery.github.io/stable/advanced.html#using-sphinx-gallery-sidebar-components
        "sg_launcher_links",
        "page-toc",
        # Sphinx-Gallery sidebar components (download buttons)
        # https://sphinx-gallery.github.io/stable/advanced.html#using-sphinx-gallery-sidebar-components
        "sg_download_links",
    ],
}

# -- Options for HTML output -------------------------------------------------
html_theme = "pydata_sphinx_theme"
html_static_path = ["_static"]
docstitle = "Health ML tutorial"

html_theme_options = {
    "github_url": "https://github.com/GaelVaroquaux/health_ml_tutorial",
    "use_edit_page_button": False,
    "show_toc_level": 2,
        "auto_examples/index": [],
    "secondary_sidebar_items": {},
}

# -- Sphinx-Gallery configuration --------------------------------------------
# The first notebook cell is prepended to every converted notebook so that
# the required packages are installed when running inside JupyterLite (Pyodide).
sphinx_gallery_conf = {
    "examples_dirs": "../examples",   # path to your example scripts
    "gallery_dirs": "auto_examples",  # path to where to save gallery generated output
    # Plot/run all file, and sort by filename
    "filename_pattern": ".*",
    "within_subsection_order": "FileNameSortKey",
    # Data files (e.g. the NHANES CSVs read by plot_predict_5yr_mortality.py)
    # are not generated by sphinx-gallery itself, so they must be copied
    # across explicitly to sit alongside the generated notebooks/scripts -
    # this is what makes the downloaded notebook and the Binder/JupyterLite
    # launchers able to find them.
    "copyfile_regex": r".*\.csv",
    # Enable the JupyterLite launch button on every gallery page.
    # sphinx-gallery will automatically copy the generated notebooks into
    # jupyterlite_contents/auto_examples/ and register that directory with
    # jupyterlite-sphinx (via post_configure_jupyterlite_sphinx).
    "jupyterlite": {
        "notebook_modification_function": None,
    },
    # Binder configuration: adds a "launch on Binder" button to every example.
    "binder": {
        "org": "GaelVaroquaux",
        "repo": "health_ml_tutorial",
        "binderhub_url": "https://mybinder.org",
        "branch": "main",
        "dependencies": "../binder/requirements.txt",
        "use_jupyter_lab": True,
    },
    # This cell is inserted at the top of every notebook produced by
    # sphinx-gallery. It installs required packages in the Pyodide environment.
    "first_notebook_cell": (
        "%pip install numpy matplotlib 'scikit-learn<1.6' pandas hazardous skrub"
    ),
}

# -- Data files for JupyterLite ------------------------------------------------
# JupyterLite runs each notebook entirely in the browser (Pyodide/WebAssembly)
# with no access to the local filesystem, so any data file an example reads
# with a relative path (e.g. plot_predict_5yr_mortality.py's
# pd.read_csv("nhanes_....csv")) must be bundled into the JupyterLite virtual
# filesystem explicitly. Sphinx-Gallery's "jupyterlite_contents" only copies
# the *generated notebooks* there, not the data files they read - see
# https://sphinx-gallery.github.io/stable/configuration.html#jupyterlite
#
# jupyterlite-sphinx's own "jupyterlite_contents" config (a list of paths,
# each copied recursively into the JupyterLite build - see
# https://jupyterlite-sphinx.readthedocs.io/en/stable/configuration.html#jupyterlite-content)
# is what we use to add the CSVs on top of what Sphinx-Gallery already adds:
# it appends its own notebook directory to this list rather than overwriting
# it, so both coexist.
#
# The CSVs are copied here (rather than committing a second copy) under
# auto_examples/, the same path the generated notebook ends up at, so that
# the notebook's relative pd.read_csv(...) resolves in the browser exactly
# like it does when Sphinx-Gallery executes the example during the build.
_jupyterlite_data_dir = os.path.join(os.path.dirname(__file__), "jupyterlite_data", "auto_examples")
os.makedirs(_jupyterlite_data_dir, exist_ok=True)
for _csv_path in glob.glob(os.path.join(os.path.dirname(__file__), "..", "examples", "*.csv")):
    shutil.copy(_csv_path, _jupyterlite_data_dir)

jupyterlite_contents = ["jupyterlite_data"]
