# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import glob
import os
import shutil
import sys

import matplotlib as _mpl

# Ensure helper modules next to conf.py are importable by string FQNs in
# sphinx_gallery_conf (e.g., reset_modules hooks).
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

# -- Project information -----------------------------------------------------
project = "Health ML Tutorial"
copyright = "2026, Gaël Varoquaux"
author = "Gaël Varoquaux"
release = "0.1"

# -- General configuration ---------------------------------------------------
# sphinx_gallery.gen_gallery must be listed before jupyterlite_sphinx so
# that sphinx-gallery's build-finished hook (create_jupyterlite_contents)
# runs before jupyterlite-sphinx's build-finished hook (jupyterlite_build).
# This ensures the notebooks are copied into jupyterlite_contents/ before
# JupyterLite is built. The config-inited ordering is handled by explicit
# priorities inside sphinx-gallery and does not depend on this order.
extensions = [
    "sphinx.ext.intersphinx",
    "sphinx_gallery.gen_gallery",
    "jupyterlite_sphinx",
]

try:
    import sphinxext.opengraph  # noqa: F401
except ImportError:
    _has_sphinxext_opengraph = False
else:
    _has_sphinxext_opengraph = True
    extensions.append("sphinxext.opengraph")

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

html_static_path = ["_static"]

html_logo = "_static/laptop-medical-solid-full.svg"

html_css_files = [
    "css/custom.css",
]

html_js_files = [
    "js/navbar-scroll.js",
]

html_sidebars = {
    "**": [
        # Sphinx-Gallery sidebar components (launch buttons)
        # https://sphinx-gallery.github.io/stable/advanced.html#using-sphinx-gallery-sidebar-components
        "sg_launcher_links",
        "page-toc",
        # Sphinx-Gallery sidebar components (download buttons)
        # https://sphinx-gallery.github.io/stable/advanced.html#using-sphinx-gallery-sidebar-components
        "sg_download_links",
    ],
    "auto_examples/index": [],
    "index": [],
}

# ---------------------------------------------------------------------------
# Configuration for intersphinx
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable", None),
    "scipy": ("https://docs.scipy.org/doc/scipy", None),
    "matplotlib": ("https://matplotlib.org/stable", None),
    "sklearn": ("https://scikit-learn.org/stable", None),
    "pandas": ("http://pandas.pydata.org/pandas-docs/stable", None),
    "seaborn": ("http://seaborn.pydata.org", None),
    "hazardous": ("https://soda-inria.github.io/hazardous", None),
}

# -- Options for HTML output -------------------------------------------------
html_theme = "pydata_sphinx_theme"
html_static_path = ["_static"]
docstitle = "Health ML tutorial"
html_baseurl = "https://gaelvaroquaux.github.io/health_ml_tutorial"

if _has_sphinxext_opengraph:
    ogp_site_url = html_baseurl
    ogp_site_name = project
    ogp_enable_meta_description = True

html_theme_options = {
    "github_url": "https://github.com/GaelVaroquaux/health_ml_tutorial",
    "use_edit_page_button": False,
    "show_toc_level": 2,
    "secondary_sidebar_items": {},
    # Adds the built-in pydata-sphinx-theme collapse/expand toggle button
    # at the bottom of the primary (left) sidebar. On small screens the
    # sidebar already collapses automatically via Bootstrap responsive
    # classes; this button lets users manually hide it on larger screens too.
    "primary_sidebar_end": ["sidebar-collapse.html"],
}

# -- Sphinx-Gallery configuration --------------------------------------------
# Parse examples/matplotlibrc once to use as the single source of truth for
# poster-style figure cosmetics across all execution environments.
_rc_file = os.path.join(os.path.dirname(__file__), "..", "examples", "matplotlibrc")
_poster_rcparams = dict(_mpl.rc_params_from_file(_rc_file, use_default_template=False))

# The first notebook cell is prepended to every converted notebook so that
# the required packages are installed when running inside JupyterLite (Pyodide).
sphinx_gallery_conf = {
    "examples_dirs": "../examples",   # path to your example scripts
    "gallery_dirs": "auto_examples",  # path to where to save gallery generated output
    # Plot/run all file, and sort by filename
    "filename_pattern": ".*",
    "within_subsection_order": "FileNameSortKey",
    # Data files (e.g. the NHANES CSVs read by plot_predict_5yr_mortality.py)
    # are not generated by sphinx-gallery itself, so they must be copied
    # across explicitly to sit alongside the generated notebooks/scripts -
    # this is what makes the downloaded notebook and the Binder/JupyterLite
    # launchers able to find them. examples/index.rst is also passed
    # through as-is (rather than auto-generated from examples/README.rst),
    # so that it can group the examples into two titled mini-galleries -
    # see examples/index.rst itself for why.
    "copyfile_regex": r".*\.(csv|rst)",
    # examples/index.rst uses the "minigallery" directive to group examples
    # by file path rather than by fully-qualified object name, so this
    # project has no use for the backreferences feature itself. It still
    # needs to be set to a directory (rather than left as the default
    # None) so that the minigallery directive does not emit a "treated as
    # file paths or globs" warning on every build - which is exactly the
    # behavior we want anyway.
    "backreferences_dir": "gen_modules/backreferences",
    # Enable the JupyterLite launch button on every gallery page.
    # sphinx-gallery will automatically copy the generated notebooks into
    # jupyterlite_contents/auto_examples/ and register that directory with
    # jupyterlite-sphinx (via post_configure_jupyterlite_sphinx).
    "jupyterlite": {
        "notebook_modification_function": None,
    },
    # Binder configuration: adds a "launch on Binder" button to every example.
    "binder": {
        "org": "GaelVaroquaux",
        "repo": "health_ml_tutorial",
        "binderhub_url": "https://mybinder.org",
        "branch": "main",
        "dependencies": "../binder/requirements.txt",
        "use_jupyter_lab": True,
    },
    # This cell is inserted at the top of every notebook produced by
    # sphinx-gallery. It installs required packages in the Pyodide environment
    # and applies the same poster-style matplotlib settings as matplotlibrc so
    # that the figures look consistent when run in JupyterLite or Binder.
    "first_notebook_cell": "\n".join([
        "%pip install numpy matplotlib 'scikit-learn' pandas hazardous skrub seaborn",
        "import matplotlib",
        f"matplotlib.rcParams.update({_poster_rcparams!r})",
    ]),
    # Poster-style rcParams re-applied before every gallery example during the
    # sphinx-gallery build (mirrors the settings in examples/matplotlibrc).
    # sphinx-gallery calls each callable in reset_modules as
    # func(gallery_conf, fname) before (and/or after) each example runs.
    # Use a fully-qualified string for the custom reset hook so
    # sphinx_gallery_conf stays cacheable under Sphinx strict warning mode.
    "reset_modules": ("matplotlib", "gallery_hooks.apply_poster_rcparams"),
}

# -- Data files for JupyterLite ------------------------------------------------
# JupyterLite runs each notebook entirely in the browser (Pyodide/WebAssembly)
# with no access to the local filesystem, so any data file an example reads
# with a relative path (e.g. plot_predict_5yr_mortality.py's
# pd.read_csv("nhanes_....csv")) must be bundled into the JupyterLite virtual
# filesystem explicitly. Sphinx-Gallery's "jupyterlite_contents" only copies
# the *generated notebooks* there, not the data files they read - see
# https://sphinx-gallery.github.io/stable/configuration.html#jupyterlite
#
# jupyterlite-sphinx's own "jupyterlite_contents" config (a list of paths,
# each copied recursively into the JupyterLite build - see
# https://jupyterlite-sphinx.readthedocs.io/en/stable/configuration.html#jupyterlite-content)
# is what we use to add the CSVs on top of what Sphinx-Gallery already adds:
# it appends its own notebook directory to this list rather than overwriting
# it, so both coexist.
#
# The CSVs are copied here (rather than committing a second copy) under
# auto_examples/, the same path the generated notebook ends up at, so that
# the notebook's relative pd.read_csv(...) resolves in the browser exactly
# like it does when Sphinx-Gallery executes the example during the build.
_jupyterlite_data_dir = os.path.join(os.path.dirname(__file__), "jupyterlite_data", "auto_examples")
os.makedirs(_jupyterlite_data_dir, exist_ok=True)
for _csv_path in glob.glob(os.path.join(os.path.dirname(__file__), "..", "examples", "*.csv")):
    shutil.copy(_csv_path, _jupyterlite_data_dir)
# Copy the matplotlibrc into the JupyterLite virtual filesystem so that
# matplotlib picks it up from the working directory when notebooks run in
# the browser (Pyodide checks the cwd for matplotlibrc at import time).
_matplotlibrc_src = os.path.join(os.path.dirname(__file__), "..", "examples", "matplotlibrc")
shutil.copy(_matplotlibrc_src, _jupyterlite_data_dir)

jupyterlite_contents = ["jupyterlite_data"]
